### PR TITLE
Fix type error on $allowAnonymous

### LINKED ISSUE #9: $allowAnonymous must not be define
PHP Compile Error 'yii\base\ErrorException' with message 'Type of leowebguy\simplemailchimp\controllers\MailchimpController::$allowAnonymous must not be defined (as in class craft\web\Controller)' 

Hi
I get this error when running the plugin. If I go into that file and comment out this line, the plugin works perfectly.
However I'm not sure how to go about overriding this properly.

### PR DESCRIPTION
**Pull request by corneliusio**
Closes #9.

### CODE REVIEW

**Comment by leowebguy** [comment]
hey cornelius,
this has changed on recent c4 versions so just update c4
it was coded in a way that works on c3/c4 php 7 and 8...

**Comment by corneliusio** [comment]
Hey, not sure I'm tracking. Currently, `composer.json` has a [platform requirement](https://github.com/leowebguy/simple-mailchimp/blob/main/composer.json#L46-L48) of `php@8.0.2` so this plugin wouldn't install on `php@7.x` as is even if it does work with Craft 3. Additionally, this error is occurring on the most recent version of Craft 4 (4.2.3) so I'm not sure what change you're referring to.

**Comment by leowebguy** [comment]
platform requirement is different from `"require": { "php": "^8.0.2" }`
the plugin installs and works fine on c3/c4 / php 7/8

**Comment by leowebguy** [comment]
if I merge your PR it will stop working on php 7, as this syntax is only valid for php8

**Comment by corneliusio** [comment]
Ah, that's my mistake on the platform requirement. That said, this plugin currently does not work with Craft 4 and this PR is the fix for that. It sounds like there need to be two separate releases for Craft 3 and 4.

**Comment by leowebguy** [comment]
hey cornelius,
took me some time to test everything, go ahead and tag `"leowebguy/simple-mailchimp": "^2.0",`
should work now

**Comment by corneliusio** [comment]
Awesome, thanks! Looks like everything is looking good.

**Pull request closed without merging**
